# Generated by Django 2.2.4 on 2019-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('gender_catagory', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=6)),
                ('catagory', models.CharField(max_length=50)),
                ('sub_catagory', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('old_price', models.IntegerField(default='0')),
                ('code', models.CharField(max_length=30)),
                ('expire_date', models.DateField()),
                ('quantity', models.IntegerField(default='1')),
                ('brand', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
