# Generated by Django 2.2.4 on 2019-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190829_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordernotes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(),
        ),
    ]
