# Generated by Django 2.2.4 on 2019-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190830_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
    ]
